backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    # - label: "Home"
    #   name: "home"
    #   file: "content/home.md"
    #   fields:
    #     - { label: "Title", name: "title", widget: "string"}
    #     - { label: "Publish Date", name: "date", widget: "datetime" }
    #     - { label: "Body", name: "body", widget: "markdown"}
    #     - label: 'Cats'
    #       name: "cats"
    #       widget: list
    #       fields:
    #         - { label: "Name", name: "name", widget: "string"}
    #         - { label: "Description", name: "description", widget: "text"}
      - label: "Galerie"
        name: galerie
        file: "content/galerie.md"
        fields: 
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
          - label: 'Cats'
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Description", name: "description", widget: "text"}
          - label: "Testimonials"
  name: "testimonials"
  widget: "list"  
  fields:
    - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
    - label: Author
      name: author
      widget: object
      fields:
        - {label: Name, name: name, widget: string, default: "Emmet"}
        - {label: Avatar, name: avatar, widget: image, default: "/img/emmet.jpg"}  