backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    # - label: "Home"
    #   name: "home"
    #   file: "content/home.md"
    #   fields:
    #     - { label: "Title", name: "title", widget: "string"}
    #     - { label: "Publish Date", name: "date", widget: "datetime" }
    #     - { label: "Body", name: "body", widget: "markdown"}
    #     - label: 'Cats'
    #       name: "cats"
    #       widget: list
    #       fields:
    #         - { label: "Name", name: "name", widget: "string"}
    #         - { label: "Description", name: "description", widget: "text"}
        file: "content/galerie.md"
      - label: "Gallery"
  name: "galleryImages"
  widget: "list"
  fields:
    - { label: "Source", name: "src", widget: "string" }
    - { label: "Alt Text", name: "alt", widget: "string" }
  default:
    - { src: "/img/tennis.jpg", alt: "Tennis" }
    - { src: "/img/footbar.jpg", alt: "Football" }
          